DDD закончил. Контексты "Управление рейсом"(flightManagemenet) и "ТО" (maintenance)
ogarose/enterprise-airport pull request #7
Opened 2021-07-03 18:01 UTC by ogarose

Доделал Domain.

В этом PR сделан контекст "Управление рейсом"(flightManagemenet) и "ТО" (maintenance).

Правда остались вопросы.
- При создании рейса есть инвариант: "ВС в эксплуатации". Для этой проверки у ВС должно быть состояние
  или это сделать через правило? Сделал правило AircraftIsInExploitation.
- В агрегатах храним только id-ки других агрегатов? 
- Билет должны быть свободны, это при форматировании заказа. У билета создать какой-то статус которые изменяется когда заказ создан 
  или какое-то правило должно это проверять? (Вопрос похож как и с ВС)
- Для заказа на билеты нужны пассажиры. Я их сделал как VO. Т.к. нигде больше они не нужны. Но есть подозрения что надо было сделать их как entity. flightManagement.Order.Passenger .
 
 Если ответите, то будет круто.
 
 По поводу vavr и either вместо exсeption.  Позже, в рамках эксперимента перепишу Maintenance контекст на него.

2021-07-06 12:31 UTC, elukianov requested changes

2021-07-06 12:31 UTC, elukianov commented on common/types/src/test/java/com/enterprise/airport/common/types/common/AircraftModelTest.java
> +        Assertions.assertEquals("777", AircraftModel.BOEING_777.getCode());
Не совсем понятно что тест проверяет. Честно говоря я бы не стал тестировать тестировать енумы

2021-07-06 12:31 UTC, elukianov commented on common/types/src/test/java/com/enterprise/airport/common/types/common/AirportTest.java
> +        Assertions.assertNotNull(Airport.TN);
Тут тоже непонятно что тест проверяет

2021-07-06 12:31 UTC, elukianov commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/aircraft/Aircraft.java
> +    private Long seatsCount;
Лучше сделать отдельный VO что-то типа Count, потому что можно даже отрицательное число сюда воктнуть

2021-07-06 12:31 UTC, elukianov commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/aircraft/AircraftIsInExploitation.java
> +public interface AircraftIsInExploitation {
Пока что предлагаю убрать это правило, так  как у нас нет возможности вывода ВС из эксплуатации

2021-07-06 12:31 UTC, elukianov commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/order/Order.java
> +    private Map<TicketId, Passenger> passengers;
Я бы тут сделал что-то типа OrderItem

2021-07-06 12:31 UTC, elukianov commented on flightManagement/domain/src/test/java/com/enterprise/airport/flightmanagement/domain/order/OrderTest.java
> +        var passenger1 = new Passenger(
Пассажиров можно в фикстуры тоже затолкать и вообще все данные для них генерировать случайные, как у нас в примере

2021-07-06 12:31 UTC, elukianov commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/order/Order.java
> +    public void pay() {
Предложение: Тут в зависимости от требований можно сделать метод идемпотентным. То есть при повтором вызове мы можем завершиться успешно, но при этом ничего не произойдет. То есть событие не отправится, статус не поменяется. Иногда бывает удобно

2021-07-06 14:04 UTC, elukianov commented
`1. При создании рейса есть инвариант: "ВС в эксплуатации". ` - см комментарии.
`2. В агрегатах храним только id-ки других агрегатов? ` - да, у нас нет цели построить полный граф всех зависимостей, ибо никакой памяти и мощности не хватит
`3. Билет должны быть свободны, это при форматировании заказа...` - ответил в звонке
`4. Для заказа на билеты нужны пассажиры. Я их сделал как VO. - это норм

2021-07-11 12:44 UTC, ogarose commented on common/types/src/test/java/com/enterprise/airport/common/types/common/AircraftModelTest.java
> +        Assertions.assertEquals("777", AircraftModel.BOEING_777.getCode());
полностью согласен. Чисто для ковереджа. Не хотел снижать его в common модуле

2021-07-11 12:44 UTC, ogarose commented on common/types/src/test/java/com/enterprise/airport/common/types/common/AirportTest.java
> +        Assertions.assertNotNull(Airport.TN);
Из той же оперы как  и предыдущий enum

2021-07-11 14:15 UTC, ogarose commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/aircraft/Aircraft.java
> +    private Long seatsCount;
done

2021-07-11 14:15 UTC, ogarose commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/aircraft/AircraftIsInExploitation.java
> +public interface AircraftIsInExploitation {
убрал

2021-07-11 14:15 UTC, ogarose commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/order/Order.java
> +    private Map<TicketId, Passenger> passengers;
норм идея, переделал

2021-07-11 14:16 UTC, ogarose commented on flightManagement/domain/src/test/java/com/enterprise/airport/flightmanagement/domain/order/OrderTest.java
> +        var passenger1 = new Passenger(
сделал. Вообще объект с фикстурами нормальная идея

2021-07-11 14:16 UTC, ogarose commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/order/Order.java
> +    public void pay() {
сделал. Интересно в рамках обучения

2021-07-13 12:05 UTC, elukianov approved these changes
Думаю вцелом норм, Сережа ещё в конце посмотрит, а пока можно мержить

2021-07-13 14:27 UTC, merged