Use case layer
ogarose/enterprise-airport pull request #8
Opened 2021-07-18 13:24 UTC by ogarose

Готов Use Case слой. Кода много, но я разделил каждый слой в свой коммит. Поэтому смотреть можно по коммитам, можно все сразу.

И как всегда вопросы которые появились пока делал этот слой.
- Не могу понять зачем создавать интерфейсы для useCase. Причем, там же где они и инмплиментируются.
 Пример com.enterprise.airport.leasing.usecase.aircraft.BuyAircraft
- Почему интерфейс UseCase идет без постфикса UseCase. А имплементация с посфиксом. Логичнее либо отказаться от интерфейсов,
либо интерфейс с UseCase постфиксом, а имплементация с Impl постфиксом.   
- Почему в проекте-примере getter UsecCas-ы типа  GetOrders не возвращают доменный объект, в новую его презентацию (типа DTO)?

2021-07-22 11:02 UTC, elukianov requested changes

2021-07-22 11:02 UTC, elukianov commented on README.MD
> +- Не могу понять зачем создавать интерфейсы для useCase. Причем там же где они и инмплиментируются.
Потому что это архитектурная граница. Между модулями мы взаимодействуем через интерфейсы, чтобы уменьшить связность.

2021-07-22 11:02 UTC, elukianov commented on README.MD
> +- Почему интерфейс UseCase идет без постфикса UseCase. А имплементация с посфиксом. Логичнее либо отказаться от интерфейсов,
Тут наверное дело вкуса как это именовать, но я не очень люблю всякие Impl. Понятное дело что это имплементация, но часто непонятно чего.

2021-07-22 11:02 UTC, elukianov commented on README.MD
> +- Почему в проекте-примере getter UsecCas-ы типа  GetOrders не возвращают доменный объект, в новую его презентацию (типа DTO)?
Можно и его, но лучше возвращать какую-то репрезентацию доменного объекта. Таким образом 
1. Мы предотвращаем протечку домена за пределы юзкейса. Для меня точка входа в программу - это юзкейс, поэтому кишками светить не хотелось бы. 
2. Мы можем вызвать какой-нибудь метод на доменном объекте и изменить его состояние, что может быть не очень.

2021-07-22 11:02 UTC, elukianov commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/flight/Flight.java
> +            AircraftId aircraftId
Тут смотри какой может быть прикол. Может получиться так, что кто-то возьмет и передаст aircraftId, просто взяв его из запроса (как раз в юзкейсе так и делается). При этом мы не знаем существует ли самолёт на самом деле. И мы не можем расчитывать на то, что у нас в базе есть поддержка целостности. Поэтому система легко приводится в неконсистентное состояние.

2021-07-22 11:02 UTC, elukianov commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/ticket/Price.java
> -    private static final int SCALE = 2;
Подозрительный знак - вытаскиваем деталь реализации наружу. Видимо это нужно для тестов. Предлагаю продублировать и сделать отдельный метод в Fixture, чтобы явно видеть что развалилось, если это значение поменяется.

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/main/java/com/enterprise/airport/flightmanagement/usecase/order/CreateOrderUseCase.java
> +                        entry -> ticketExtractor.findById(entry.getKey())
На будущее: тут мы можем предположить, что загружать билеты оптимальнее пачками, поэтому можем определить специальный интерфейс

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/main/java/com/enterprise/airport/flightmanagement/usecase/order/CreateOrderUseCase.java
> +    public static class IllegalTicketIdException extends DomainException {
Здесь и далее. На этом уровне уже не доменные ошибки, а ошибки уровня приложения. И вот на следующем уровне может начаться путаница. Это как раз то, что решает Either. Но думаю для учебного примера пока можно оставить, тем более, что ты ещё хотел попробовать сделать через Either

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/Fixtures.java
> +                new AircraftId(987L),
Рандомы можно и в различные идентификаторы тоже затолкать

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/flight/AnnounceFlightUseCaseTest.java
> +    private FlightPersisterUtil flightPersister;
Лучше избегать общего состояния в юнит тестах, потому что потом будет тяжело паралелить

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/aircraft/TakeNewAircraftUseCaseTest.java
> +        Assertions.assertEquals(request.getId(), aircraftId);
Не проверяется взаимодействие с хранилищем. Пожохе забыл

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/order/CreateOrderUseCaseTest.java
> +                Map.of(
Такие длинные штуки тоже можно куда-нибудть в fixtures спрятать, чтобы тест был чище и нагляднее

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/rules/AircraftIsOccupiedByAnotherFlightImplTest.java
> +                        Airport.AC,
Тоже можно в фикстуры засунуть

2021-07-22 11:02 UTC, elukianov commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/util/AircraftPersisterUtil.java
> +public class AircraftPersisterUtil implements AircraftPersister {
Этот и остальные. Лучше не Util называть, а прямо тем, чем оно является - Fake либо InMemoryAircraftPersister

2021-07-22 11:02 UTC, elukianov commented on maintenance/usecase/src/test/java/com/enterprise/airport/maintenance/usecase/flight/FinishFlightUseCaseTest.java
> +        Assertions.assertEquals(request.getFlightHours(), flight.getFlightHours());
Нет проверки взаимодействия, надо будет проверить везде

2021-07-23 14:37 UTC, ogarose commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/flight/AnnounceFlightUseCaseTest.java
> +    private FlightPersisterUtil flightPersister;
Не хватает опыта в  java. Особо еще не сталкивался с проблемами парралелизма еще. Может можешь подсказать чего-нибудь почитать на эту тему?

2021-07-23 15:28 UTC, ogarose commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/flight/Flight.java
> +            AircraftId aircraftId
хороший аргумент. вернул на место

2021-07-23 15:28 UTC, ogarose commented on flightManagement/domain/src/main/java/com/enterprise/airport/flightmanagement/domain/ticket/Price.java
> -    private static final int SCALE = 2;
исправил

2021-07-23 15:28 UTC, ogarose commented on flightManagement/usecase/src/main/java/com/enterprise/airport/flightmanagement/usecase/order/CreateOrderUseCase.java
> +                        entry -> ticketExtractor.findById(entry.getKey())
расширил интерфейс

2021-07-23 15:29 UTC, ogarose commented on flightManagement/usecase/src/main/java/com/enterprise/airport/flightmanagement/usecase/order/CreateOrderUseCase.java
> +    public static class IllegalTicketIdException extends DomainException {
Вроде немного разобрался с Either. Попытаюсь переписать часть в воскресенье

2021-07-23 15:29 UTC, ogarose commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/Fixtures.java
> +                new AircraftId(987L),
сделал

2021-07-23 15:29 UTC, ogarose commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/aircraft/TakeNewAircraftUseCaseTest.java
> +        Assertions.assertEquals(request.getId(), aircraftId);
сделал

2021-07-23 15:30 UTC, ogarose commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/order/CreateOrderUseCaseTest.java
> +                Map.of(
мне тоже понравилась идея с прятаньем всего в фикстуры. Тесты действительно проще читать

2021-07-23 15:30 UTC, ogarose commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/rules/AircraftIsOccupiedByAnotherFlightImplTest.java
> +                        Airport.AC,
сделал

2021-07-23 15:30 UTC, ogarose commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/util/AircraftPersisterUtil.java
> +public class AircraftPersisterUtil implements AircraftPersister {
переименовал в fake

2021-07-23 15:31 UTC, ogarose commented on maintenance/usecase/src/test/java/com/enterprise/airport/maintenance/usecase/flight/FinishFlightUseCaseTest.java
> +        Assertions.assertEquals(request.getFlightHours(), flight.getFlightHours());
сделал spy через который проверяем взаимодествие

2021-07-27 08:34 UTC, elukianov commented on flightManagement/usecase/src/test/java/com/enterprise/airport/flightmanagement/usecase/flight/AnnounceFlightUseCaseTest.java
> +    private FlightPersisterUtil flightPersister;
Классика - это Java Concurrency in Practice, есть и на русском. Но тут я скорее о том, что у тебя методы могут запускаться в непредсказуемый момент и в таком же непредсказуемом порядке. И если у тебя есть общее состояние между тестами, то это приведет к случайным падениям.

2021-07-27 08:37 UTC, elukianov approved these changes

2021-07-30 06:38 UTC, merged