Either error handling for Maintenance module
ogarose/enterprise-airport pull request #9
Opened 2021-07-31 18:32 UTC by ogarose

Переписал модуль Maintenance с Domain Exception на использование BusinessError с Either из Vavr.  Если интересно, то посмотрите плиз.

Вроде где-то лучше получилось. Где-то хуже.

2021-08-11 13:23 UTC, elukianov requested changes

2021-08-11 13:23 UTC, elukianov commented on common/types/src/main/java/com/enterprise/airport/common/types/error/GeneralUseCaseError.java
> +public  class GeneralUseCaseError extends UseCaseError {
Думаю что это логичнее поместить в другой модуль, здесь подразумевались типы для домена

2021-08-11 13:23 UTC, elukianov commented on common/types/src/main/java/com/enterprise/airport/common/types/error/GeneralUseCaseError.java
> +    private final Object errorObject;
Можно типизировать ошибку через дженерик <T>

2021-08-15 12:20 UTC, ogarose commented on common/types/src/main/java/com/enterprise/airport/common/types/error/GeneralUseCaseError.java
> +public  class GeneralUseCaseError extends UseCaseError {
разделил модуль common.types на common.types.domain и common.types.usecase

2021-08-15 12:20 UTC, ogarose commented on common/types/src/main/java/com/enterprise/airport/common/types/error/GeneralUseCaseError.java
> +    private final Object errorObject;
done

2021-08-15 14:48 UTC, merged